// Shared admin UI primitives — inline styles, no animation, font uses --font-inter

export const s = {
  h1: {
    fontFamily: "var(--font-inter)",
    fontWeight: 800 as const,
    fontSize: 24,
    color: "var(--foreground)",
    marginBottom: 24,
    letterSpacing: "-0.02em",
  },
  label: {
    display: "block" as const,
    fontFamily: "var(--font-inter)",
    fontSize: 12,
    color: "var(--muted)",
    marginBottom: 5,
    textTransform: "uppercase" as const,
    letterSpacing: "0.05em",
  },
  input: {
    width: "100%",
    fontFamily: "var(--font-inter)",
    fontSize: 14,
    padding: "9px 12px",
    borderRadius: 8,
    border: "1px solid var(--border)",
    background: "var(--background)",
    color: "var(--foreground)",
    outline: "none",
    display: "block" as const,
  },
  textarea: {
    width: "100%",
    fontFamily: "var(--font-inter)",
    fontSize: 14,
    padding: "9px 12px",
    borderRadius: 8,
    border: "1px solid var(--border)",
    background: "var(--background)",
    color: "var(--foreground)",
    outline: "none",
    resize: "vertical" as const,
    minHeight: 80,
    display: "block" as const,
  },
  btn: {
    fontFamily: "var(--font-inter)",
    fontWeight: 700 as const,
    fontSize: 13,
    padding: "9px 18px",
    borderRadius: 8,
    border: "none",
    background: "var(--foreground)",
    color: "var(--background)",
    cursor: "pointer",
  },
  btnDanger: {
    fontFamily: "var(--font-inter)",
    fontSize: 12,
    padding: "5px 12px",
    borderRadius: 6,
    border: "1px solid #fca5a5",
    background: "transparent",
    color: "#ef4444",
    cursor: "pointer",
  },
  btnOutline: {
    fontFamily: "var(--font-inter)",
    fontSize: 12,
    padding: "5px 12px",
    borderRadius: 6,
    border: "1px solid var(--border)",
    background: "transparent",
    color: "var(--foreground)",
    cursor: "pointer",
    textDecoration: "none" as const,
    display: "inline-block" as const,
  },
  field: { marginBottom: 16 },
  card: {
    padding: "24px",
    borderRadius: 14,
    border: "1px solid var(--border)",
    background: "var(--surface)",
    marginBottom: 12,
  },
  row: {
    display: "flex" as const,
    alignItems: "center" as const,
    justifyContent: "space-between" as const,
    gap: 12,
  },
  divider: {
    height: 1,
    background: "var(--border)",
    margin: "32px 0",
  },
  grid2: {
    display: "grid" as const,
    gridTemplateColumns: "1fr 1fr",
    gap: 16,
  },
};
